[package]
name = "effractor-server"
description = "The effractor binary: app shell, embedded assets, share API."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true

[[bin]]
name = "effractor"
path = "src/main.rs"

[dependencies]

[lints]
workspace = true
